# Generated by Django 3.2.9 on 2021-11-15 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_properties_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='hire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='agent',
            name='is_mvp',
            field=models.BooleanField(default=False),
        ),
    ]
