# Generated by Django 3.2.9 on 2021-11-16 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20211115_2005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Properties',
            new_name='Listing',
        ),
    ]
