# Generated by Django 3.2.9 on 2021-11-16 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_properties_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='landlord',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='listing',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.agent'),
        ),
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
