# Generated by Django 3.2.9 on 2021-11-16 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20211116_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='password',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='phone',
        ),
        migrations.AddField(
            model_name='landlord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='listing',
            name='landlord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.landlord'),
        ),
    ]
