# Generated by Django 3.2.9 on 2021-11-16 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20211116_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='created_at',
        ),
    ]
