# Generated by Django 3.2.9 on 2021-11-16 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_agent_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='image1',
            new_name='image',
        ),
    ]
