# Generated by Django 3.2.9 on 2021-11-16 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_listing_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='slug',
        ),
    ]
